# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 7
      uses: actions/setup-java@v1
      with:
        java-version: 7

    - name: Install Junit
      run: |
        mkdir junit
        curl https://search.maven.org/remotecontent?filepath=junit/junit/4.13/junit-4.13.jar --output ./junit/junit.jar
        curl https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar --ouput ./junit/hamcrest.jar
        export JUNIT_HOME=$(pwd)/junit
        export PATH=$PATH:$JUNIT_HOME
        export CLASSPATH=$CLASSPATH:$JUNIT_HOME/junit.jar:$JUNIT_HOME/hamcrest.jar

    - name: Build
      run: make build

    - name: Test
      run: make test
